### ISSUE TITLE
Error: Cannot find module stylelint_wrapper.js

### ISSUE THREAD

**Issue by Akurganow** [kungfusheep/SublimeLinter-contrib-stylelint#1]
Try to lint example `untitled.css` file (with only one empty block) that what i have in sublime console:

``` bash
SublimeLinter: stylelint: untitled.css ['/usr/local/opt/nvm/versions/node/v0.12.7/bin/node', '/Users/akurganow/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-contrib-stylelint.sublime-package/stylelint_wrapper.js', '@', '--config', '/Users/akurganow/Projects/.stylelintrc'] 
SublimeLinter: stylelint output:
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/akurganow/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-contrib-stylelint.sublime-package/stylelint_wrapper.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3 
```

**Comment by kungfusheep** [comment]
As a workaround to this issue, you can clone this repo into your `Sublime Text 3\Packages` directory and you should be fine until I can get a fix out. 

Thanks for reporting.

**Comment by kungfusheep** [comment]
I'd missed a `.no-sublime-package` file, which was causing the paths to screw up and point at the `.sublime-package` file - which is essentially a zip file. I've added the file and bumped the version, so it should be available as an update on package control shortly. I'll close the bug after confirming this has fixed it.

**Comment by kungfusheep** [comment]
I can confirm 1.0.1 fixes this path issue. 

Thanks again for reporting! 

Closing.

**Comment by kungfusheep** [comment]
As a side note - you may potentially have to remove the package from sublime, restart and then re-install via package control to fully fix the issue.  Sorry for any inconvenience.

**Comment by Akurganow** [comment]
Thanks! Now it's work great

**Comment by kungfusheep** [comment]
👍
