### ISSUE TITLE
Incompatible with PostCSS syntax package

### ISSUE THREAD

**Issue by JamesJosephFinn** [kungfusheep/SublimeLinter-contrib-stylelint#10]
Does not lint when syntax is set to PostCSS using the [SublimeText PostCSS Syntax Highlighting Package](https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS).

@hudochenkov perhaps the issue is with your plugin.

**Comment by hudochenkov** [comment]
I've sent PR to this plugin.

**Comment by JamesJosephFinn** [comment]
@hudochenkov thank you!
