### ISSUE TITLE
No errors being picked up from stylelint output

### ISSUE THREAD

**Issue by chrislam** [kungfusheep/SublimeLinter-contrib-stylelint#25]
Looks like the output format of stylelint has changed to and no longer matches the regex which parses the output for errors and their details.

Any ETA on supporting this new format? it's possible that the json output format of stylelint could be leveraged instead to hopefully provide a more robust solution here as then the stylelint_wrapper.js would be in control of the format of the output passed to the regex.

**Comment by Arkkimaagi** [comment]
I was able to get it somewhat working with this regular expression, it has the command name in it also in a kind of ugly way, but I kind of prefer seeing that information too.

Change the regular expression in `linter.py` file:

``` Python
r'^ *(?P<line>[0-9]+)\:(?P<col>[0-9]+) *(?P<message>.+)'
```

I do agree that having a JSON parser or even a custom javascript formatter for the data would be the best option compared to this regexp stuff.
