### ISSUE TITLE
Not linting

### ISSUE THREAD

**Issue by JamesJosephFinn** [kungfusheep/SublimeLinter-contrib-stylelint#5]
Sorry I'm not of much help, but I'm at my wits end on this one.

Here's the console printout:

``` bash
SublimeLinter: chdir not set or invalid, using /Users/jamesfinn/Documents/MechanicMedia/Website/src/css/modules 
SublimeLinter: stylelint: _buttons.css ['/usr/local/bin/node', '/Users/jamesfinn/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/stylelint_wrapper.js', '@', '--config', '/Users/jamesfinn/Documents/MechanicMedia/Website/.stylelintrc'] 
SublimeLinter: stylelint output:
undefined:10
        "selector-class-pattern": [ 2, "^(?:u|is|has)\-[a-z][a-zA-Z0-9]*$|^(?!u|is|has)[a-zA-Z][a-zA-Z0-9]*(?:\-[a-z][a-zA-Z0-9]*)?(?:\-\-[a-z][a-zA-Z0-9]*)?$" ]
                                                      ^

SyntaxError: Unexpected number
    at Object.parse (native)
    at Object.<anonymous> (/Users/jamesfinn/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/stylelint_wrapper.js:11:19)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```
- `stylelint` is installed both locally as a dev-dependency, and globally.
- `postcss` is installed both locally as a dev-dependency, and globally.
- `postcss-cli` is installed globally.
- `postcss` and `stylelint` are commands accessible in my `$PATH`.
- I have a `.stylelintrc` file in my project root which extends `stylelint-config-suitcss`, which is also installed as a dev-dependency.
- I've uninstalled and re-installed everything to do with this problem using npm and Package Control. All my ducks are in a row, the darn thing just won't lint.

**Comment by kungfusheep** [comment]
Hi, I've made some changes to the wrapper tonight. It will now invoke the stylelint CLI and not try to parse the rc if the CLI is available. Could you let me know if 1.0.4 fixes your issue? Thanks.

**Comment by JamesJosephFinn** [comment]
Works like a charm. :+1:  Thanks a lot. I like tools that help me to be a better perfectionist. Stylelint is the way of the future.
