### ISSUE TITLE
Support .stylelintrc yaml syntax

### ISSUE THREAD

**Issue by Nitive** [kungfusheep/SublimeLinter-contrib-stylelint#7]
Now yaml syntax doesn't work
Sublime console output:

```
SublimeLinter: stylelint output:
undefined:1
rules:
^

SyntaxError: Unexpected token r
```

---

It happens because you parse file with `JSON.parse` [stylelint_wrapper.js#L11](https://github.com/kungfusheep/SublimeLinter-contrib-stylelint/blob/master/stylelint_wrapper.js#L11)
Stylelint use [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) to get config.
Can I create PR to replace `JSON.parse` with cosmiconfig?

**Comment by kungfusheep** [comment]
Hi - I've updated the wrapper to use the stylelint CLI where available, so this should start to work now given that the wrapper won't attempt to read the rc if it detects it will be using the CLI. Cheers

**Comment by Nitive** [comment]
Thanks!
